USE ROLE ACCOUNTADMIN;

-- CREATE WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS NETFLIX_DBT_WH WITH WAREHOUSE_SIZE='X-SMALL';
USE WAREHOUSE NETFLIX_DBT_WH;

-- CREATE DATABASE & SCHEMA
CREATE DATABASE IF NOT EXISTS NETFLIX_DBT_DB;
USE DATABASE NETFLIX_DBT_DB;

CREATE SCHEMA IF NOT EXISTS NETFLIX_DBT_DB.RAW;

-- CREATE ROLE & ASSIGN GRANTS
CREATE ROLE IF NOT EXISTS NETFLIX_DBT_ROLE;
GRANT ROLE NETFLIX_DBT_ROLE TO ROLE ACCOUNTADMIN;

-- ASSIGN PERMISSIONS
GRANT USAGE ON WAREHOUSE NETFLIX_DBT_WH TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON DATABASE NETFLIX_DBT_DB TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE NETFLIX_DBT_DB TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NETFLIX_DBT_DB TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NETFLIX_DBT_DB.RAW TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NETFLIX_DBT_DB.RAW TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON ALL STAGES IN DATABASE NETFLIX_DBT_DB TO ROLE NETFLIX_DBT_ROLE;
GRANT ALL ON FUTURE STAGES IN DATABASE NETFLIX_DBT_DB TO ROLE NETFLIX_DBT_ROLE;

-- CREATE USER AND ASSIGN ROLE TO USER
CREATE USER IF NOT EXISTS NETFLIX_DBT_USER
    PASSWORD='dbtPassword123'
    LOGIN_NAME='NETFLIX_DBT_USER'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='NETFLIX_DBT_WH'
    DEFAULT_ROLE=NETFLIX_DBT_ROLE
    DEFAULT_NAMESPACE='NETFLIX_DBT_DB.RAW'
    COMMENT='DBT USER FOR DATA TRANSFORMATION - NETFLIX PROJECT';
ALTER USER NETFLIX_DBT_USER SET TYPE = LEGACY_SERVICE;
GRANT ROLE NETFLIX_DBT_ROLE TO USER NETFLIX_DBT_USER;

